<?php

/**
 * BaseaBlogItemCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $blog_item_id
 * @property integer $blog_category_id
 * @property aBlogItem $BlogItem
 * @property aBlogCategory $BlogCategory
 * 
 * @method integer           getBlogItemId()       Returns the current record's "blog_item_id" value
 * @method integer           getBlogCategoryId()   Returns the current record's "blog_category_id" value
 * @method aBlogItem         getBlogItem()         Returns the current record's "BlogItem" value
 * @method aBlogCategory     getBlogCategory()     Returns the current record's "BlogCategory" value
 * @method aBlogItemCategory setBlogItemId()       Sets the current record's "blog_item_id" value
 * @method aBlogItemCategory setBlogCategoryId()   Sets the current record's "blog_category_id" value
 * @method aBlogItemCategory setBlogItem()         Sets the current record's "BlogItem" value
 * @method aBlogItemCategory setBlogCategory()     Sets the current record's "BlogCategory" value
 * 
 * @package    cropping
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseaBlogItemCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_blog_item_category');
        $this->hasColumn('blog_item_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('blog_category_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('aBlogItem as BlogItem', array(
             'local' => 'blog_item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('aBlogCategory as BlogCategory', array(
             'local' => 'blog_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}