<?php

/**
 * BaseaBlogEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property sfGuardUser $Author
 * @property aBlogCategory $Category
 * 
 * @method sfGuardUser   getAuthor()   Returns the current record's "Author" value
 * @method aBlogCategory getCategory() Returns the current record's "Category" value
 * @method aBlogEvent    setAuthor()   Sets the current record's "Author" value
 * @method aBlogEvent    setCategory() Sets the current record's "Category" value
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7380 2010-03-15 21:07:50Z jwage $
 */
abstract class BaseaBlogEvent extends aBlogItem
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Author', array(
             'local' => 'author_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('aBlogCategory as Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));
    }
}